const DEFAULT_FONT_SIZE = 16

// Modeling the Solar System using Star and Planet classes

const SOLAR_SYSTEM_RADIUS_IN_AU = 200//1000//sol to inner edge of oort cloud //200*1000 //sol to outer edge of oort cloud
const INNER_SOLAR_SYSTEM_RADIUS_IN_AU = 30.1 //distance sol to neptune

const SOLAR_RADII_PER_AU = 215.032
const EARTH_RADII_PER_AU = 23454.8
const MILES_PER_AU = 432288*EARTH_RADII_PER_AU

//TODO: try to make some of these vars more dynamic in future - different sizes for ships, projectiles etc.
const FLEET_RADIUS = 1/1000 * 1/EARTH_RADII_PER_AU

const PLANET_ENCOUNTER_CHANCE_PER_DAY = 0.2; //chance of random encounter per day when right next to an 'average' planet
const ASTEROIDS_ENCOUNTER_CHANCE_PER_DAY = 0.5; //chance of fooroid storms when in the middle of an asteroid belt
const BANK_BOUNTY_CHANCE_PER_DAY = 0.01;
const NEWS_CHANCE_PER_DAY = 1/30;
const META_NEWS_CHANCE_PER_DAY = 1/365

//combat distances = miles, time = seconds
const ENCOUNTER_SHIP_MAX_SPAWN_DISTANCE_RATIO = 0.5
const ENCOUNTER_MAP_RADIUS_MILES = 100
const BASE_SHIP_RADIUS_IN_MILES = 1/2
const AVERAGE_SHIP_MASS = 1
const AVERAGE_FLEET_SPEED = 1000 //in AU per year
const AVERGE_RAMMING_KNOCKBACK_DISTANCE = 1 //in miles

const STARTING_SKILL_POINTS = 5;
const SKILL_POINTS_PER_LEVEL = 5;
const CAPTAIN_LEVELS_PER_OFFICER = 3;

const AVERAGE_EXP_FROM_COMBAT = 20;
const AVERAGE_EXP_FROM_MINING = 15;
const AVERAGE_EXP_FROM_ESCAPING = 10;

const MARKET_AVERAGE_CARGO_PER_TYPE = 20
const MARKET_AVERAGE_CREDITS = 200*1000
const MARKET_MAX_CARGO_PRICE_MODIFIER = 5
const MARKET_MIN_CARGO_PRICE_MODIFIER = 1/5
const MARKET_AVERAGE_CARGO_PRICE_MODIFIER = (MARKET_MAX_CARGO_PRICE_MODIFIER + MARKET_MIN_CARGO_PRICE_MODIFIER) / 2
const ACADEMY_MAX_SKILL_PRICE_MODIFIER = 3
const ACADEMY_MIN_SKILL_PRICE_MODIFIER = 1/3
const ACADEMY_AVERAGE_SKILL_PRICE_MODIFIER = (ACADEMY_MAX_SKILL_PRICE_MODIFIER + ACADEMY_MIN_SKILL_PRICE_MODIFIER) / 2

const SHIPYARD_AVERAGE_NUM_SHIPS = 3
const SHIPYARD_AVERAGE_NUM_MODULES = 2
const GUILD_AVERAGE_NUM_OFFICERS = 3

const STARTING_CREDITS = 5*1000

const AVERAGE_SHIP_HULL = 15
const AVERAGE_SHIP_SHIELDS = 10
const AVERAGE_SHIP_LASERS = 5
const AVERAGE_SHIP_ENGINE = 5
const AVERAGE_SHIP_CARGO_SPACE = 5
const AVERAGE_SHIP_RADARS = 5

const AVERAGE_SHIP_MOVE_DISTANCE = 7.5
const AVERAGE_SHIP_ATTACK_DISTANCE = 40 //have increased this a lot because you can miss now
const AVERAGE_SHIP_LASER_DMG = 5
const AVERAGE_SHIP_RAM_DMG = 2.5

const BANK_MAX_LOAN_YEARS = 5
const BANK_MIN_LOAN_AMOUNT = 100
const BANK_AVERAGE_CREDITS = 50*1000

const SHIP_NUM_MOVES_PER_TURN = 2

const JAIL_DAYS_PER_1000CR_FINE = 5 //5 days of jail time per 1000CR of fine


const GAME_START_YEAR = 3000
const GAME_END_YEAR = 3100

const AMBIENT_EFFECT_MIN_RADIUS_MODIFIER = 2
const AMBIENT_EFFECT_MAX_RADIUS_MODIFIER = 2

const STAR_MAP_YEARS_PER_MS = 1/365/24/60 * 2

const NEWS_MAX_AGE = 60

