console.log("Generating moons...");

// Earth's Moon (Luna)
const LUNA = new Moon("Luna", hexToRgba('#cccccc'), 0.273, new Orbit(0.00257), PLANET_TYPES.TERRESTRIAL, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.HIGH_RADIATION, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 27.3, 0);
LUNA.parent = EARTH;

// Mars' Moons
const PHOBOS = new Moon("Phobos", hexToRgba('#888888'), 0.00178, new Orbit(0.0000627), PLANET_TYPES.TERRESTRIAL, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 0.32, 0);
PHOBOS.parent = MARS;
const DEIMOS = new Moon("Deimos", hexToRgba('#999999'), 0.000977, new Orbit(0.000157), PLANET_TYPES.TERRESTRIAL, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 1.26, 0);
DEIMOS.parent = MARS;

// Jupiter's Major Moons (Galilean)
const IO = new Moon("Io", hexToRgba('#ffff00'), 0.286, new Orbit(0.00282), PLANET_TYPES.TERRESTRIAL, null, null,
    null,
    [PLANET_FEATURE_TYPES.VOLCANIC_ACTIVITY, PLANET_FEATURE_TYPES.THIN_ATMOSPHERE, PLANET_FEATURE_TYPES.HIGH_RADIATION, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 1.77, 0); //, PLANET_FEATURE_TYPES.SULFUR_SURFACE
IO.parent = JUPITER;
const EUROPA = new Moon("Europa", hexToRgba('#ddeeff'), 0.245, new Orbit(0.00448), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.THIN_ATMOSPHERE, PLANET_FEATURE_TYPES.SUBSURFACE_OCEAN, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.HIGH_RADIATION, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 3.55, 0);
EUROPA.parent = JUPITER;
const GANYMEDE = new Moon("Ganymede", hexToRgba('#bbb8aa'), 0.413, new Orbit(0.00715), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.THIN_ATMOSPHERE, PLANET_FEATURE_TYPES.SUBSURFACE_OCEAN, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.HIGH_RADIATION, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.WEAK_MAGNETOSPHERE], 7.15, 0);
GANYMEDE.parent = JUPITER;
const CALLISTO = new Moon("Callisto", hexToRgba('#8b7d6b'), 0.378, new Orbit(0.0126), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.THIN_ATMOSPHERE, PLANET_FEATURE_TYPES.SUBSURFACE_OCEAN, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.HIGH_RADIATION, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 16.69, 0);
CALLISTO.parent = JUPITER;

// Saturn's Major Moons
const MIMAS = new Moon("Mimas", hexToRgba('#e0e0e0'), 0.0311, new Orbit(0.00124), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 0.94, 0);
MIMAS.parent = SATURN;
const ENCELADUS = new Moon("Enceladus", hexToRgba('#ffffff'), 0.0396, new Orbit(0.00159), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.THIN_ATMOSPHERE, PLANET_FEATURE_TYPES.SUBSURFACE_OCEAN, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.ICE_GEYSERS, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 1.37, 0);
ENCELADUS.parent = SATURN;
const TETHYS = new Moon("Tethys", hexToRgba('#f0f0f0'), 0.0844, new Orbit(0.00197), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 1.89, 0);
TETHYS.parent = SATURN;
const TITAN = new Moon("Titan", hexToRgba('#ffcc66'), 0.404, new Orbit(0.00816), PLANET_TYPES.TERRESTRIAL, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.THICK_ATMOSPHERE, PLANET_FEATURE_TYPES.DENSE_CLOUDS, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 15.95, 0);
TITAN.parent = SATURN;
const RHEA = new Moon("Rhea", hexToRgba('#d5d5d5'), 0.120, new Orbit(0.00352), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.THIN_ATMOSPHERE, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 4.52, 0);
RHEA.parent = SATURN;

// Uranus' Major Moons
const MIRANDA = new Moon("Miranda", hexToRgba('#cccccc'), 0.0372, new Orbit(0.000863), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 1.41, 0);
MIRANDA.parent = URANUS;
const ARIEL = new Moon("Ariel", hexToRgba('#d0d0d0'), 0.0911, new Orbit(0.00127), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 2.52, 0);
ARIEL.parent = URANUS;
const UMBRIEL = new Moon("Umbriel", hexToRgba('#7a7a7a'), 0.0918, new Orbit(0.00178), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 4.14, 0);
UMBRIEL.parent = URANUS;
const TITANIA = new Moon("Titania", hexToRgba('#b8b8b8'), 0.124, new Orbit(0.00291), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 8.71, 0);
TITANIA.parent = URANUS;
const OBERON = new Moon("Oberon", hexToRgba('#8a8a8a'), 0.120, new Orbit(0.00390), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 13.46, 0);
OBERON.parent = URANUS;

// Neptune's Major Moons
const TRITON = new Moon("Triton", hexToRgba('#ffccdd'), 0.212, new Orbit(0.00237), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.THIN_ATMOSPHERE, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.ICE_GEYSERS, PLANET_FEATURE_TYPES.CRYOVOLCANISM, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 5.88, 0);
TRITON.parent = NEPTUNE;
const PROTEUS = new Moon("Proteus", hexToRgba('#999999'), 0.0330, new Orbit(0.000785), PLANET_TYPES.TERRESTRIAL, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 1.12, 0);
PROTEUS.parent = NEPTUNE;

// Pluto's Moon (Charon - large binary companion)
const CHARON = new Moon("Charon", hexToRgba('#998877'), 0.0951, new Orbit(0.000131), PLANET_TYPES.ICE_DWARF, null, null,
    null,
    [PLANET_FEATURE_TYPES.EXTREMELY_COLD, PLANET_FEATURE_TYPES.NO_ATMOSPHERE, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.LOW_GRAVITY, PLANET_FEATURE_TYPES.TIDALLY_LOCKED, PLANET_FEATURE_TYPES.NO_MAGNETOSPHERE], 6.39, 0);
CHARON.parent = PLUTO;

// Moon arrays by parent planet
const EARTH_MOONS = [LUNA]
const MARS_MOONS = [PHOBOS, DEIMOS]
const JUPITER_MOONS = [IO, EUROPA, GANYMEDE, CALLISTO]
const SATURN_MOONS = [MIMAS, ENCELADUS, TETHYS, TITAN, RHEA]
const URANUS_MOONS = [MIRANDA, ARIEL, UMBRIEL, TITANIA, OBERON]
const NEPTUNE_MOONS = [TRITON, PROTEUS]
const PLUTO_MOONS = [CHARON]

// Add moons array to each planet
EARTH.addChildren(EARTH_MOONS)
MARS.addChildren(MARS_MOONS)
JUPITER.addChildren(JUPITER_MOONS)
SATURN.addChildren(SATURN_MOONS)
URANUS.addChildren(URANUS_MOONS)
NEPTUNE.addChildren(NEPTUNE_MOONS)
PLUTO.addChildren(PLUTO_MOONS)

// Planets without major moons
/*MERCURY.children = []
VENUS.children = []
CERES.children = []
ERIS.children = []
HAUMEA.children = []
MAKEMAKE.children = []*/

// All moons collection
const MOONS_ALL = [
    ...EARTH_MOONS,
    ...MARS_MOONS,
    ...JUPITER_MOONS,
    ...SATURN_MOONS,
    ...URANUS_MOONS,
    ...NEPTUNE_MOONS,
    ...PLUTO_MOONS
]

SOLAR_SYSTEM.moons = MOONS_ALL

// Log moon counts
console.log("=== MOON COUNTS ===")
console.log("Total Moons:", MOONS_ALL.length)
console.log("  - Earth Moons:", EARTH_MOONS.length)
console.log("  - Mars Moons:", MARS_MOONS.length)
console.log("  - Jupiter Moons:", JUPITER_MOONS.length)
console.log("  - Saturn Moons:", SATURN_MOONS.length)
console.log("  - Uranus Moons:", URANUS_MOONS.length)
console.log("  - Neptune Moons:", NEPTUNE_MOONS.length)
console.log("  - Pluto Moons:", PLUTO_MOONS.length)
console.log("===================")