console.log("Generating solar system...");

const SOL = new Star("Sol", hexToRgba('#ffff44'), 109, 0, 0);

const MERCURY = new Planet("Mercury", hexToRgba('#aaaaaa'), 0.383, 0, 0, new Orbit(0.39), PLANET_TYPES.TERRESTRIAL, null, null, 
    new Climate(TEMPERATURES.EXTREMELY_HIGH, ATMOSPHERIC_PRESSURES.NONE, GRAVITIES.LOW, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.EXTREMELY_LOW, MAGNETOSPHERES.VERY_LOW, RADIATION_LEVELS.VERY_HIGH),
    [PLANET_FEATURE_TYPES.IMPACT_BASIN, PLANET_FEATURE_TYPES.SMOOTH_SURFACE],
    PLANET_ATMOSPHERE_TYPES.NONE, null, PLANET_GEOLOGY_TYPES.SILICATE_IRON, 58.6);
const VENUS = new Planet("Venus", hexToRgba('#e5c07b'), 0.949, 0, 0, new Orbit(0.72), PLANET_TYPES.GAS_DWARF, null, null,
    new Climate(TEMPERATURES.MOLTEN, ATMOSPHERIC_PRESSURES.CRUSHING, GRAVITIES.SLIGHTLY_LOW, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.VERY_HIGH, MAGNETOSPHERES.EXTREMELY_LOW, RADIATION_LEVELS.SLIGHTLY_HIGH),
    [PLANET_FEATURE_TYPES.RETROGRADE_ROTATION, PLANET_FEATURE_TYPES.GREENHOUSE_EFFECT, PLANET_FEATURE_TYPES.DENSE_CLOUDS, PLANET_FEATURE_TYPES.VOLCANIC_ACTIVITY],
    PLANET_ATMOSPHERE_TYPES.CARBON_DIOXIDE, null, PLANET_GEOLOGY_TYPES.BASALTIC, 243);
const EARTH = new Planet("Earth", hexToRgba('#4a90e2'), 1.0, 0, 0, new Orbit(1.0), PLANET_TYPES.EARTHLIKE, null, null,
    new Climate(TEMPERATURES.MEDIUM, ATMOSPHERIC_PRESSURES.MEDIUM, GRAVITIES.MEDIUM, OCEAN_COVERAGES.VERY_HIGH, GEOLOGICAL_ACTIVITIES.SLIGHTLY_HIGH, MAGNETOSPHERES.MEDIUM, RADIATION_LEVELS.VERY_LOW),
    [PLANET_FEATURE_TYPES.STRONG_MAGNETOSPHERE, PLANET_FEATURE_TYPES.LARGE_SATELLITE, PLANET_FEATURE_TYPES.ICE_CAPS],
    PLANET_ATMOSPHERE_TYPES.OXYGEN_NITROGEN, PLANET_OCEAN_TYPES.WATER, PLANET_GEOLOGY_TYPES.GRANITE, 1.0);
const MARS = new Planet("Mars", hexToRgba('#b22222'), 0.532, 0, 0, new Orbit(1.52), PLANET_TYPES.TERRESTRIAL, null, null,
    new Climate(TEMPERATURES.LOW, ATMOSPHERIC_PRESSURES.EXTREMELY_LOW, GRAVITIES.LOW, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.VERY_LOW, MAGNETOSPHERES.EXTREMELY_LOW, RADIATION_LEVELS.LOW),
    [PLANET_FEATURE_TYPES.MASSIVE_CANYON, PLANET_FEATURE_TYPES.ICE_CAPS, PLANET_FEATURE_TYPES.IMPACT_BASIN],
    PLANET_ATMOSPHERE_TYPES.CARBON_DIOXIDE, null, PLANET_GEOLOGY_TYPES.BASALTIC, 1.03);
const JUPITER = new Planet("Jupiter", hexToRgba('#d2b48c'), 11.21, 0, 0, new Orbit(5.2), PLANET_TYPES.GAS_GIANT, null, null,
    new Climate(TEMPERATURES.VERY_LOW, ATMOSPHERIC_PRESSURES.CRUSHING, GRAVITIES.EXTREMELY_HIGH, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.EXTREMELY_HIGH, MAGNETOSPHERES.EXTREMELY_HIGH, RADIATION_LEVELS.EXTREMELY_HIGH),
    [PLANET_FEATURE_TYPES.GREAT_STORM, PLANET_FEATURE_TYPES.STRONG_MAGNETOSPHERE, PLANET_FEATURE_TYPES.RADIATION_BELTS, PLANET_FEATURE_TYPES.FAINT_RINGS, PLANET_FEATURE_TYPES.TROJAN_ASTEROIDS],
    PLANET_ATMOSPHERE_TYPES.HYDROGEN_HELIUM, null, null, 0.41);
const SATURN = new Planet("Saturn", hexToRgba('#f5deb3'), 9.45, 0, 0, new Orbit(9.58), PLANET_TYPES.GAS_GIANT, null, null,
    new Climate(TEMPERATURES.VERY_LOW, ATMOSPHERIC_PRESSURES.CRUSHING, GRAVITIES.VERY_HIGH, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.HIGH, MAGNETOSPHERES.HIGH, RADIATION_LEVELS.SLIGHTLY_HIGH),
    [PLANET_FEATURE_TYPES.RING_SYSTEM],
    PLANET_ATMOSPHERE_TYPES.HYDROGEN_HELIUM, null, null, 0.45);
const URANUS = new Planet("Uranus", hexToRgba('#afeeee'), 4.01, 0, 0, new Orbit(19.2), PLANET_TYPES.ICE_GIANT, null, null,
    new Climate(TEMPERATURES.EXTREMELY_LOW, ATMOSPHERIC_PRESSURES.VERY_HIGH, GRAVITIES.SLIGHTLY_HIGH, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.LOW, MAGNETOSPHERES.SLIGHTLY_HIGH, RADIATION_LEVELS.LOW),
    [PLANET_FEATURE_TYPES.EXTREME_AXIAL_TILT, PLANET_FEATURE_TYPES.FAINT_RINGS, PLANET_FEATURE_TYPES.METHANE_ATMOSPHERE],
    PLANET_ATMOSPHERE_TYPES.HYDROGEN_HELIUM, null, PLANET_GEOLOGY_TYPES.CARBON, 0.72);
const NEPTUNE = new Planet("Neptune", hexToRgba('#4169e1'), 3.88, 0, 0, new Orbit(30.05), PLANET_TYPES.ICE_GIANT, null, null,
    new Climate(TEMPERATURES.EXTREMELY_LOW, ATMOSPHERIC_PRESSURES.VERY_HIGH, GRAVITIES.SLIGHTLY_HIGH, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.SLIGHTLY_HIGH, MAGNETOSPHERES.SLIGHTLY_HIGH, RADIATION_LEVELS.LOW),
    [PLANET_FEATURE_TYPES.GREAT_STORM, PLANET_FEATURE_TYPES.METHANE_ATMOSPHERE],
    PLANET_ATMOSPHERE_TYPES.HYDROGEN_HELIUM, null, PLANET_GEOLOGY_TYPES.CARBON, 0.67);

// Dwarf Planets
const CERES = new Planet("Ceres", hexToRgba('#999999'), 0.076, 0, 0, new Orbit(2.77), PLANET_TYPES.TERRESTRIAL, null, null,
    new Climate(TEMPERATURES.EXTREMELY_LOW, ATMOSPHERIC_PRESSURES.NONE, GRAVITIES.EXTREMELY_LOW, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.VERY_LOW, MAGNETOSPHERES.NONE, RADIATION_LEVELS.LOW),
    [PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.SUBSURFACE_OCEAN],
    PLANET_ATMOSPHERE_TYPES.NONE, PLANET_OCEAN_TYPES.SUBSURFACE_WATER, PLANET_GEOLOGY_TYPES.WATER_ICE, 0.38);
const PLUTO = new Planet("Pluto", hexToRgba('#d4a373'), 0.186, 0, 0, new Orbit(39.48), PLANET_TYPES.TERRESTRIAL, null, null,
    new Climate(TEMPERATURES.EXTREMELY_LOW, ATMOSPHERIC_PRESSURES.EXTREMELY_LOW, GRAVITIES.EXTREMELY_LOW, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.SLIGHTLY_LOW, MAGNETOSPHERES.NONE, RADIATION_LEVELS.LOW),
    [PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.NITROGEN_ATMOSPHERE, PLANET_FEATURE_TYPES.BINARY_SYSTEM],
    PLANET_ATMOSPHERE_TYPES.NITROGEN, null, PLANET_GEOLOGY_TYPES.MIXED_ICE, 6.4);
const ERIS = new Planet("Eris", hexToRgba('#cccccc'), 0.182, 0, 0, new Orbit(67.7), PLANET_TYPES.TERRESTRIAL, null, null,
    new Climate(TEMPERATURES.EXTREMELY_LOW, ATMOSPHERIC_PRESSURES.NONE, GRAVITIES.EXTREMELY_LOW, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.EXTREMELY_LOW, MAGNETOSPHERES.NONE, RADIATION_LEVELS.VERY_LOW),
    [PLANET_FEATURE_TYPES.WATER_ICE_SURFACE],
    PLANET_ATMOSPHERE_TYPES.NONE, null, PLANET_GEOLOGY_TYPES.WATER_ICE, 1.1);
const HAUMEA = new Planet("Haumea", hexToRgba('#e8e8e8'), 0.128, 0, 0, new Orbit(43.13), PLANET_TYPES.TERRESTRIAL, null, null,
    new Climate(TEMPERATURES.EXTREMELY_LOW, ATMOSPHERIC_PRESSURES.NONE, GRAVITIES.EXTREMELY_LOW, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.EXTREMELY_LOW, MAGNETOSPHERES.NONE, RADIATION_LEVELS.VERY_LOW),
    [PLANET_FEATURE_TYPES.ELONGATED_SHAPE, PLANET_FEATURE_TYPES.RAPID_ROTATION, PLANET_FEATURE_TYPES.WATER_ICE_SURFACE],
    PLANET_ATMOSPHERE_TYPES.NONE, null, PLANET_GEOLOGY_TYPES.WATER_ICE, 0.16);
const MAKEMAKE = new Planet("Makemake", hexToRgba('#c9a687'), 0.116, 0, 0, new Orbit(45.79), PLANET_TYPES.TERRESTRIAL, null, null,
    new Climate(TEMPERATURES.EXTREMELY_LOW, ATMOSPHERIC_PRESSURES.EXTREMELY_LOW, GRAVITIES.EXTREMELY_LOW, OCEAN_COVERAGES.NONE, GEOLOGICAL_ACTIVITIES.EXTREMELY_LOW, MAGNETOSPHERES.NONE, RADIATION_LEVELS.VERY_LOW),
    [PLANET_FEATURE_TYPES.WATER_ICE_SURFACE, PLANET_FEATURE_TYPES.METHANE_ATMOSPHERE],
    PLANET_ATMOSPHERE_TYPES.METHANE, null, PLANET_GEOLOGY_TYPES.METHANE_ICE, 0.95);

const PLANETS = [MERCURY, VENUS, EARTH, MARS, JUPITER, SATURN, URANUS, NEPTUNE]
const DWARF_PLANETS = [CERES, PLUTO, ERIS, HAUMEA, MAKEMAKE]

SOL.addChildren([...PLANETS, ...DWARF_PLANETS])


const CORONA = new AsteroidBelt("Corona", ASTEROID_BELT_TYPES.Plasma, hexToRgba('#ffff00'), 0.1, 0, 0, new Orbit(0.1), [ENCOUNTER_TYPES.PLASMOIDS], [EFFECT_TYPES.ION_CLOUD, EFFECT_TYPES.PLASMA_TRAIL])
const ASTEROID_BELT = new AsteroidBelt("Asteroid Belt", ASTEROID_BELT_TYPES.Rocky, hexToRgba('#bb8844'), 0.2*2.8, 0, 0, new Orbit(2.8), [ENCOUNTER_TYPES.ASTEROIDS], [EFFECT_TYPES.DEBRIS_CLOUD])
const TROJANS = new AsteroidBelt("Trojan Asteroids", ASTEROID_BELT_TYPES.Rocky, hexToRgba('#bbbb88'), 0.5, 60, 0, new Orbit(5.2), [ENCOUNTER_TYPES.ASTEROIDS], [EFFECT_TYPES.DEBRIS_CLOUD])
const GREEKS = new AsteroidBelt("Greek Asteroids", ASTEROID_BELT_TYPES.Rocky, hexToRgba('#bbbb88'), 0.5, -60, 0, new Orbit(5.2), [ENCOUNTER_TYPES.ASTEROIDS], [EFFECT_TYPES.DEBRIS_CLOUD])
const KUIPER_BELT = new AsteroidBelt("Kuiper Belt", ASTEROID_BELT_TYPES.Icy, hexToRgba('#bbbbdd'), 50*2/5, 0, 0, new Orbit(50), [ENCOUNTER_TYPES.CRYOIDS], [EFFECT_TYPES.ICE_CLOUD])

const ASTEROIDS = generateAsteroids(ASTEROID_BELT, COLORS.Brown, 500, 3, 0.2)
const KUIPER_ASTEROIDS = generateAsteroids(KUIPER_BELT, COLORS.LightBlue, 5000, 5, 2/5)
const TROJAN_ASTEROIDS = generateAsteroids(TROJANS, COLORS.Gray, 100, 2, 0.1, JUPITER.orbit.progressOffset + 0.15, 0.1)
const GREEK_ASTEROIDS = generateAsteroids(GREEKS, COLORS.Gray, 100, 2, 0.1, JUPITER.orbit.progressOffset - 0.15, 0.1)
const SOLAR_FLARES = generateAsteroids(CORONA, COLORS.LightOrange, 100, 0.1, 0.25)

const ALL_ASTEROIDS = [...ASTEROIDS, ...KUIPER_ASTEROIDS, ...TROJAN_ASTEROIDS, ...GREEK_ASTEROIDS, ...SOLAR_FLARES]

SOL.addChildren(ALL_ASTEROIDS)

const BACKGROUND_STARS = generateBackgroundStars(SOLAR_SYSTEM_RADIUS_IN_AU, 5000)

const SOLAR_SYSTEM = new StarSystem(
    'Sol System',
    hexToRgba('#ffff44'),
    KUIPER_BELT.orbit.radius,
    0, 0,
    SOL, [SOL],
    [...PLANETS, ...DWARF_PLANETS],
    [],
    [CORONA, ASTEROID_BELT, TROJANS, GREEKS, KUIPER_BELT], [...ALL_ASTEROIDS],
    BACKGROUND_STARS
);

console.log("Generated solar system:", SOLAR_SYSTEM)

