
/**
 * Represents a type of fleet that can be encountered.
 * @class FleetType
 */
class FleetType {
    /**
     * @param {string} name - The name of the fleet type.
     * @param {ShipType[]} shipTypes - The types of ships this fleet can contain.
     * @param {number} minShips - The minimum number of ships in this fleet type.
     * @param {number} maxShips - The maximum number of ships in this fleet type.
     * @param {number} maxCredits - The maximum credits this fleet can carry.
     * @param {CargoType[]} cargoTypes - The types of cargo this fleet can carry.
     * @param {number} voyageYears - The voyage duration in years for this fleet type.
     */
    constructor(name = '', shipTypes = [], minShips = 1, maxShips = 1, maxCredits = 1, cargoTypes = [], voyageYears = 0.08, targetMaxDistance = Infinity) {
        /** @type {string} */
        this.name = name
        /** @type {ShipType[]} */
        this.shipTypes = shipTypes
        /** @type {number} */
        this.minShips = minShips
        /** @type {number} */
        this.maxShips = maxShips
        /** @type {number} */
        this.voyageYears = voyageYears
        /** @type {number} */
        this.targetMaxDistance = targetMaxDistance
        /** @type {number} */
        this.maxCredits = maxCredits
        /** @type {CargoType[]} */
        this.cargoTypes = cargoTypes
    }
}

class PseudoFleetType extends FleetType {
    constructor(name = '', shipTypes = [], minShips = 1, maxShips = 1, cargoTypes = []) {
        super(name, shipTypes, minShips, maxShips, 0, cargoTypes, 0)
    }
}

const AVG_CR = 5000 //something like a basic unit of credits per fleet
const AVG_DR = 1/2 //average voyage is max 6 months

const FLEET_TYPES = {
    SOLDIERS: new FleetType('Soldiers', [SHIP_TYPES.BATTLESHIP, SHIP_TYPES.FRIGATE, SHIP_TYPES.DESTROYER], 3, 7, AVG_CR*CL.LOW, [CARGO_TYPES.FOOD, CARGO_TYPES.WATER, CARGO_TYPES.WEAPONS, CARGO_TYPES.ANTIMATTER], AVG_DR*CL.SLIGHTLY_HIGH, CHASE_DISTANCES.NEAR),
    MERCENARIES: new FleetType('Mercenaries', [SHIP_TYPES.FRIGATE, SHIP_TYPES.DESTROYER, SHIP_TYPES.FIGHTER], 2, 6, AVG_CR*CL.HIGH, [CARGO_TYPES.FOOD, CARGO_TYPES.WATER, CARGO_TYPES.WEAPONS], AVG_DR*CL.SLIGHTLY_HIGH, CHASE_DISTANCES.NEAR),
    POLICE: new FleetType('Police', [SHIP_TYPES.INTERCEPTOR], 1, 5, AVG_CR*CL.LOW, [], AVG_DR*CL.SLIGHTLY_LOW, CHASE_DISTANCES.FAR),
    BOUNTY_HUNTERS: new FleetType('Bounty Hunters', [SHIP_TYPES.DESTROYER, SHIP_TYPES.INTERCEPTOR, SHIP_TYPES.SCOUT, SHIP_TYPES.JAMMER], 1, 2, AVG_CR*CL.MEDIUM, [], AVG_DR*CL.MEDIUM, CHASE_DISTANCES.FAR),

    INQUISITORS: new FleetType('Inquisitors', [SHIP_TYPES.DESTROYER, SHIP_TYPES.FIRE_SHIP], 2, 4, AVG_CR*CL.HIGH, [CARGO_TYPES.WEAPONS, CARGO_TYPES.RELICS], AVG_DR*CL.HIGH, CHASE_DISTANCES.NEAR),
    PIRATES: new FleetType('Pirates', [SHIP_TYPES.FIGHTER, SHIP_TYPES.FRIGATE, SHIP_TYPES.BATTLESHIP, SHIP_TYPES.FIRE_SHIP], 1, 5, AVG_CR*CL.VERY_HIGH, CARGO_TYPES_ALL, AVG_DR*CL.MEDIUM, CHASE_DISTANCES.NEAR),
    SLAVERS: new FleetType('Slavers', [SHIP_TYPES.FIGHTER, SHIP_TYPES.INTERCEPTOR, SHIP_TYPES.PASSENGER_SHIP], 2, 4, AVG_CR*CL.HIGH, [], AVG_DR*CL.MEDIUM, CHASE_DISTANCES.NEAR),
    REBELS: new FleetType('Rebels', [SHIP_TYPES.FIGHTER, SHIP_TYPES.BLOCKADE_RUNNER, SHIP_TYPES.FIRE_SHIP], 2, 4, AVG_CR*CL.SLIGHTLY_HIGH, [CARGO_TYPES.WEAPONS, CARGO_TYPES.WEAPONS, CARGO_TYPES.HOLOCUBES, CARGO_TYPES.WEAPONS], 0),

    TAX_COLLECTORS: new FleetType('Tax Collectors', [SHIP_TYPES.COURIER_SHIP, SHIP_TYPES.ESCORT_SHIP, SHIP_TYPES.SUPPLY_SHIP], 1, 2, AVG_CR*CL.ASTRONOMICAL, [], AVG_DR*CL.VERY_LOW, CHASE_DISTANCES.MEDIUM),
    MERCHANTS: new FleetType('Merchants', [SHIP_TYPES.TANKER, SHIP_TYPES.SUPPLY_SHIP, SHIP_TYPES.ESCORT_SHIP], 1, 5, AVG_CR*CL.EXTREMELY_HIGH, CARGO_TYPES_ALL.filter(ct=>(!ct.illegal)), AVG_DR*CL.SLIGHTLY_HIGH),
    MINERS: new FleetType('Miners', [SHIP_TYPES.DRILLING_RIG, SHIP_TYPES.TANKER], 1, 3, AVG_CR*CL.VERY_LOW, [CARGO_TYPES.FOOD, CARGO_TYPES.WATER, CARGO_TYPES.METAL, CARGO_TYPES.ISOTOPES], AVG_DR*CL.EXTREMELY_HIGH, Infinity),
    SALVAGERS: new FleetType('Salvagers', [SHIP_TYPES.TUG_SHIP, SHIP_TYPES.TANKER, SHIP_TYPES.UTILITY_SHIP], 1, 3, AVG_CR*CL.SLIGHTLY_HIGH, CARGO_TYPES_ALL, AVG_DR*CL.SLIGHTLY_HIGH, Infinity),
    TOURISTS: new FleetType('Tourists', [SHIP_TYPES.PASSENGER_SHIP, SHIP_TYPES.ESCORT_SHIP], 1, 3, AVG_CR*CL.EXTREMELY_HIGH, [CARGO_TYPES.FOOD, CARGO_TYPES.WATER, CARGO_TYPES.DRUGS, CARGO_TYPES.HOLOCUBES], AVG_DR*CL.VERY_HIGH, CHASE_DISTANCES.NEAR),
    COLONISTS: new FleetType('Colonists', [SHIP_TYPES.PASSENGER_SHIP, SHIP_TYPES.DRILLING_RIG, SHIP_TYPES.ESCORT_SHIP], 1, 3, AVG_CR*CL.SLIGHTLY_LOW, [CARGO_TYPES.FOOD, CARGO_TYPES.WATER], AVG_DR*CL.EXTREMELY_HIGH),
    SCIENTISTS: new FleetType('Scientists', [SHIP_TYPES.SCOUT, SHIP_TYPES.COURIER_SHIP], 1, 3, AVG_CR*CL.LOW, [CARGO_TYPES.RELICS, CARGO_TYPES.ISOTOPES, CARGO_TYPES.NANITES, CARGO_TYPES.ANTIMATTER], AVG_DR*CL.EXTREMELY_HIGH, CHASE_DISTANCES.EXTREME),
    PILGRIMS: new FleetType('Pilgrims', [SHIP_TYPES.PASSENGER_SHIP], 1, 3, AVG_CR*CL.EXTREMELY_LOW, [CARGO_TYPES.FOOD, CARGO_TYPES.WATER, CARGO_TYPES.RELICS], AVG_DR*CL.VERY_HIGH),
    MISSIONARIES: new FleetType('Missionaries', [SHIP_TYPES.COURIER_SHIP, SHIP_TYPES.UTILITY_SHIP], 1, 2, AVG_CR*CL.LOW, [CARGO_TYPES.FOOD, CARGO_TYPES.WATER, CARGO_TYPES.RELICS], AVG_DR*CL.HIGH, CHASE_DISTANCES.MEDIUM),
    DIPLOMATS: new FleetType('Diplomats', [SHIP_TYPES.COURIER_SHIP, SHIP_TYPES.FRIGATE], 1, 2, AVG_CR*CL.VERY_HIGH, [CARGO_TYPES.FOOD, CARGO_TYPES.WATER, CARGO_TYPES.HOLOCUBES], AVG_DR*CL.HIGH, CHASE_DISTANCES.EXTREME),
    REFUGEES: new FleetType('Refugees', [SHIP_TYPES.PASSENGER_SHIP, SHIP_TYPES.SUPPLY_SHIP, SHIP_TYPES.TUG_SHIP], 2, 5, AVG_CR*CL.EXTREMELY_LOW, [CARGO_TYPES.FOOD, CARGO_TYPES.WATER, CARGO_TYPES.FOOD, CARGO_TYPES.WATER], AVG_DR*CL.HIGH),
    SMUGGLERS: new FleetType('Smugglers', [SHIP_TYPES.BLOCKADE_RUNNER], 1, 3, AVG_CR*CL.VERY_HIGH, [CARGO_TYPES.DRUGS, CARGO_TYPES.ANTIMATTER, CARGO_TYPES.WEAPONS], AVG_DR*CL.MEDIUM),
    SYNDICATES: new FleetType('Syndicates', [SHIP_TYPES.DESTROYER, SHIP_TYPES.FIGHTER], 2, 4, AVG_CR*CL.EXTREMELY_HIGH, [CARGO_TYPES.DRUGS, CARGO_TYPES.WEAPONS, CARGO_TYPES.ANTIMATTER, CARGO_TYPES.DRUGS], AVG_DR*CL.VERY_LOW, CHASE_DISTANCES.NEAR),
    EXPLORERS: new FleetType('Explorers', [SHIP_TYPES.SCOUT, SHIP_TYPES.SUPPLY_SHIP], 1, 3, AVG_CR*CL.MEDIUM, [CARGO_TYPES.ISOTOPES, CARGO_TYPES.ANTIMATTER, CARGO_TYPES.RELICS, CARGO_TYPES.HOLOCUBES], AVG_DR*CL.ASTRONOMICAL),
    PERFORMERS: new FleetType('Performers', [SHIP_TYPES.FIRE_SHIP, SHIP_TYPES.JAMMER], 1, 3, AVG_CR*CL.SLIGHTLY_LOW, [CARGO_TYPES.HOLOCUBES], AVG_DR*CL.HIGH, CHASE_DISTANCES.NEAR),
    HACKERS: new FleetType('Hackers', [SHIP_TYPES.JAMMER, SHIP_TYPES.BLOCKADE_RUNNER, SHIP_TYPES.UTILITY_SHIP], 1, 2, AVG_CR*CL.HIGH, [CARGO_TYPES.DRUGS, CARGO_TYPES.NANITES, CARGO_TYPES.HOLOCUBES], AVG_DR*CL.LOW, CHASE_DISTANCES.NEAR),
    MEDIA: new FleetType('Media', [SHIP_TYPES.JAMMER, SHIP_TYPES.COURIER_SHIP, SHIP_TYPES.SCOUT], 1, 2, AVG_CR*CL.SLIGHTLY_LOW, [CARGO_TYPES.HOLOCUBES, CARGO_TYPES.NANITES], AVG_DR*CL.HIGH, CHASE_DISTANCES.EXTREME),
    AGENTS: new FleetType('Agents', [SHIP_TYPES.JAMMER, SHIP_TYPES.BLOCKADE_RUNNER], 1, 2, AVG_CR*CL.VERY_HIGH, [CARGO_TYPES.DRUGS, CARGO_TYPES.WEAPONS, CARGO_TYPES.ANTIMATTER], AVG_DR*CL.EXTREMELY_HIGH, CHASE_DISTANCES.EXTREME),
    COMMISSARS: new FleetType('Commissars', [SHIP_TYPES.DESTROYER, SHIP_TYPES.INTERCEPTOR], 1, 3, AVG_CR*CL.MEDIUM, [CARGO_TYPES.WEAPONS, CARGO_TYPES.FOOD], AVG_DR*CL.LOW, CHASE_DISTANCES.NEAR),
}

const PSEUDO_FLEET_TYPES = {
    ABANDONED_SHIP: new PseudoFleetType('Abandoned Ship', [...SHIP_TYPES_ALL], 1, 1, CARGO_TYPES_ALL),
    ASTEROIDS_STORM: new PseudoFleetType('Asteroid Storm', [ASTEROID_SHIP_TYPES.ASTEROID], 20, 30, [CARGO_TYPES.METAL, CARGO_TYPES.WATER, CARGO_TYPES.METAL, CARGO_TYPES.WATER, CARGO_TYPES.METAL, CARGO_TYPES.WATER, CARGO_TYPES.ISOTOPES]),
    ASTEROIDS_CALM: new PseudoFleetType('Asteroid Field', [ASTEROID_SHIP_TYPES.ASTEROID], 5, 15, [CARGO_TYPES.METAL, CARGO_TYPES.WATER, CARGO_TYPES.METAL, CARGO_TYPES.WATER, CARGO_TYPES.METAL, CARGO_TYPES.WATER, CARGO_TYPES.ISOTOPES]),
    CRYOIDS_STORM: new PseudoFleetType('Cryoid Storm', [ASTEROID_SHIP_TYPES.CRYOID], 20, 30, [CARGO_TYPES.METAL, CARGO_TYPES.WATER, CARGO_TYPES.WATER, CARGO_TYPES.WATER, CARGO_TYPES.ISOTOPES]),
    CRYOIDS_CALM: new PseudoFleetType('Cryoid Field', [ASTEROID_SHIP_TYPES.CRYOID], 5, 15, [CARGO_TYPES.METAL, CARGO_TYPES.WATER, CARGO_TYPES.WATER, CARGO_TYPES.WATER, CARGO_TYPES.ISOTOPES]),
    PLASMOIDS_STORM: new PseudoFleetType('Plasmoid Storm', [ASTEROID_SHIP_TYPES.PLASMOID], 20, 30, [CARGO_TYPES.ANTIMATTER]),
    PLASMOIDS_CALM: new PseudoFleetType('Plasmoid Field', [ASTEROID_SHIP_TYPES.PLASMOID], 5, 15, [CARGO_TYPES.ANTIMATTER]),
    MAGNETOIDS_STORM: new PseudoFleetType('Magnetoid Storm', [ASTEROID_SHIP_TYPES.MAGNETOID], 20, 30, [CARGO_TYPES.ISOTOPES]),
    MAGNETOIDS_CALM: new PseudoFleetType('Magnetoid Field', [ASTEROID_SHIP_TYPES.MAGNETOID], 5, 15, [CARGO_TYPES.ISOTOPES]),
    // Legacy names for backward compatibility
}

const FLEET_TYPES_ALL = Object.values(FLEET_TYPES)

const PLAYER_FLEET_TYPE = new FleetType('Player Fleet', [], 0, 0, 0, [], 0)
