/**
 * Represents a type of policy for a planet's civilization.
 * @class PolicyType
 */
class PolicyType {
    /**
     * @param {string} name - The name of the policy type.
     * @param {NewsFlavor} flavor - The news flavor associated with this policy type.
     * @param {number[]} color - The color associated with this policy type.
     * @param {GovernmentType[]} forbiddenGovs - Government types that cannot adopt this policy.
     * @param {GovernmentType[]} favoriteGovs - Government types that are more likely to adopt this policy.
     * @param {NewsType[]} forbiddenNewsTypes - News types that cannot occur on this planet when policy is active.
     * @param {NewsType[]} favoriteNewsTypes - News types that are 3x more likely when policy is active.
     * @param {NewsType[]} immuneNewsTypes - News types that cannot target this planet when policy is active.
     * @param {Map<FactionType, number>} factionSpawnModifiers - Modifiers to fleet spawn rates for factions under this policy.
     */
    constructor(name = '', flavor = new NewsFlavor(), color = COLORS.White, forbiddenGovs = [], favoriteGovs = [], forbiddenNewsTypes = [], favoriteNewsTypes = [], immuneNewsTypes = [], factionSpawnModifiers = new Map()) {
        /** @type {string} */
        this.name = name
        /** @type {NewsFlavor} */
        this.flavor = flavor
        /** @type {number[]} */
        this.color = color
        /** @type {GovernmentType[]} */
        this.forbiddenGovs = forbiddenGovs
        /** @type {GovernmentType[]} */
        this.favoriteGovs = favoriteGovs
        /** @type {NewsType[]} */
        this.forbiddenNewsTypes = forbiddenNewsTypes
        /** @type {NewsType[]} */
        this.favoriteNewsTypes = favoriteNewsTypes
        /** @type {NewsType[]} */
        this.immuneNewsTypes = immuneNewsTypes
        /** @type {Map<FactionType, number>} */
        this.factionSpawnModifiers = factionSpawnModifiers
    }
}

const PT = {
    // Economic Policies
    DECENTRALIZATION: new PolicyType('Decentralization', NF.ECONOMY, COLORS.LightGreen, [GT.COMMUNISM], [GT.ANARCHY], 
        [], [], [NT.STOCK_MARKET_CRASH], 
        new Map([[FACTION_TYPES.MERCHANTS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.MINERS, CL.HIGH], [FACTION_TYPES.SMUGGLERS, CL.HIGH], [FACTION_TYPES.SALVAGERS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.TAX_COLLECTORS, CL.EXTREMELY_LOW], [FACTION_TYPES.REBELS, CL.HIGH], [FACTION_TYPES.EXPLORERS, CL.HIGH], [FACTION_TYPES.PERFORMERS, CL.SLIGHTLY_HIGH]])),
    PROTECTIONISM: new PolicyType('Protectionism', NF.ECONOMY, COLORS.Orange, [GT.ANARCHY], [GT.ARISTOCRACY, GT.POLICE_STATE], 
        [NT.TRADE_AGREEMENT], [NT.SCARCITY, NT.SURPLUS], [NT.BLOCKADE, NT.SANCTIONS],
        new Map([[FACTION_TYPES.MERCHANTS, CL.EXTREMELY_LOW], [FACTION_TYPES.SMUGGLERS, CL.VERY_HIGH], [FACTION_TYPES.POLICE, CL.SLIGHTLY_HIGH], [FACTION_TYPES.DIPLOMATS, CL.VERY_LOW], [FACTION_TYPES.TAX_COLLECTORS, CL.HIGH], [FACTION_TYPES.BOUNTY_HUNTERS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.SYNDICATES, CL.HIGH], [FACTION_TYPES.EXPLORERS, CL.VERY_LOW], [FACTION_TYPES.PERFORMERS, CL.LOW]])),
    CENTRAL_PLANNING: new PolicyType('Central Planning', NF.ECONOMY, COLORS.Red, [GT.ANARCHY, GT.CORPORATISM], [GT.COMMUNISM, GT.TECHNOCRACY], 
        [NT.STOCK_MARKET_CRASH, NT.BANKRUPTCY], [NT.CONSTRUCTION], [],
        new Map([[FACTION_TYPES.MINERS, CL.HIGH], [FACTION_TYPES.MERCHANTS, CL.LOW], [FACTION_TYPES.POLICE, CL.HIGH], [FACTION_TYPES.TAX_COLLECTORS, CL.VERY_HIGH], [FACTION_TYPES.MERCENARIES, CL.SLIGHTLY_LOW], [FACTION_TYPES.SYNDICATES, CL.EXTREMELY_LOW], [FACTION_TYPES.EXPLORERS, CL.LOW], [FACTION_TYPES.PERFORMERS, CL.VERY_LOW]])),
    FREE_TRADE: new PolicyType('Free Trade', NF.ECONOMY, COLORS.Yellow, [GT.COMMUNISM], [GT.CORPORATISM, GT.DEMOCRACY], 
        [NT.ISOLATIONISM], [NT.TRADE_AGREEMENT, NT.INVESTMENT, NT.TOURISM], [],
        new Map([[FACTION_TYPES.MERCHANTS, CL.VERY_HIGH], [FACTION_TYPES.TOURISTS, CL.HIGH], [FACTION_TYPES.SMUGGLERS, CL.LOW], [FACTION_TYPES.DIPLOMATS, CL.VERY_HIGH], [FACTION_TYPES.MERCENARIES, CL.SLIGHTLY_HIGH], [FACTION_TYPES.EXPLORERS, CL.HIGH], [FACTION_TYPES.PERFORMERS, CL.VERY_HIGH], [FACTION_TYPES.SYNDICATES, CL.SLIGHTLY_HIGH]])),
    
    // Labor Policies
    FORCED_LABOR: new PolicyType('Forced Labor', NF.LABOR, COLORS.Brown, [GT.DEMOCRACY, GT.ANARCHY], [GT.POLICE_STATE, GT.COMMUNISM], 
        [], [NT.CONSTRUCTION, NT.INDUSTRIAL_ACCIDENT], [NT.CIVIL_STRIFE],
        new Map([[FACTION_TYPES.POLICE, CL.HIGH], [FACTION_TYPES.SLAVERS, CL.VERY_HIGH], [FACTION_TYPES.COLONISTS, CL.EXTREMELY_LOW], [FACTION_TYPES.REBELS, CL.VERY_HIGH], [FACTION_TYPES.MERCENARIES, CL.SLIGHTLY_HIGH], [FACTION_TYPES.BOUNTY_HUNTERS, CL.HIGH], [FACTION_TYPES.EXPLORERS, CL.EXTREMELY_LOW], [FACTION_TYPES.PERFORMERS, CL.EXTREMELY_LOW]])),
    FEUDALISM: new PolicyType('Feudalism', NF.LABOR, COLORS.DarkMagenta, [GT.COMMUNISM, GT.ANARCHY], [GT.ARISTOCRACY], 
        [], [NT.RAIDING, NT.LAND_GRAB], [NT.DEMOCRACY_MOVEMENT],
        new Map([[FACTION_TYPES.SOLDIERS, CL.HIGH], [FACTION_TYPES.PIRATES, CL.SLIGHTLY_HIGH], [FACTION_TYPES.MERCHANTS, CL.LOW], [FACTION_TYPES.MERCENARIES, CL.VERY_HIGH], [FACTION_TYPES.BOUNTY_HUNTERS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.SYNDICATES, CL.SLIGHTLY_HIGH], [FACTION_TYPES.PERFORMERS, CL.SLIGHTLY_LOW]])),
    LAISSEZ_FAIRE: new PolicyType('Laissez Faire', NF.LABOR, COLORS.DarkYellow, [], [GT.TECHNOCRACY, GT.CORPORATISM], 
        [NT.FORCED_LABOR], [NT.ECONOMIC_BOOM, NT.TRADE_AGREEMENT, NT.STOCK_MARKET_CRASH, NT.DEPRESSION, NT.BANKRUPTCY, NT.INDUSTRIAL_ACCIDENT], [],
        new Map([[FACTION_TYPES.MERCHANTS, CL.HIGH], [FACTION_TYPES.MINERS, CL.HIGH], [FACTION_TYPES.PIRATES, CL.SLIGHTLY_HIGH], [FACTION_TYPES.SALVAGERS, CL.HIGH], [FACTION_TYPES.MERCENARIES, CL.HIGH], [FACTION_TYPES.BOUNTY_HUNTERS, CL.HIGH], [FACTION_TYPES.SYNDICATES, CL.VERY_HIGH], [FACTION_TYPES.EXPLORERS, CL.HIGH], [FACTION_TYPES.PERFORMERS, CL.HIGH]])),
    LABOR_UNIONS: new PolicyType('Labor Unions', NF.LABOR, COLORS.Blue, [], [GT.DEMOCRACY, GT.COMMUNISM], 
        [NT.FORCED_LABOR], [], [],
        new Map([[FACTION_TYPES.MINERS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.SLAVERS, CL.EXTREMELY_LOW], [FACTION_TYPES.POLICE, CL.SLIGHTLY_LOW], [FACTION_TYPES.MERCENARIES, CL.SLIGHTLY_LOW], [FACTION_TYPES.SYNDICATES, CL.LOW], [FACTION_TYPES.PERFORMERS, CL.SLIGHTLY_HIGH]])),
    
    // Social/Cultural Policies
    ETHNIC_NATIONALISM: new PolicyType('Ethnic Nationalism', NF.CULTURE, COLORS.LightMagenta, [GT.ANARCHY], [GT.POLICE_STATE, GT.ARISTOCRACY], 
        [NT.IMMIGRATION], [NT.GENOCIDE, NT.LAND_GRAB, NT.CRACKDOWN, NT.EUGENICS], [],
        new Map([[FACTION_TYPES.SOLDIERS, CL.VERY_HIGH], [FACTION_TYPES.POLICE, CL.HIGH], [FACTION_TYPES.TOURISTS, CL.EXTREMELY_LOW], [FACTION_TYPES.COLONISTS, CL.EXTREMELY_LOW], [FACTION_TYPES.REBELS, CL.HIGH], [FACTION_TYPES.REFUGEES, CL.VERY_HIGH], [FACTION_TYPES.MERCENARIES, CL.HIGH], [FACTION_TYPES.BOUNTY_HUNTERS, CL.HIGH], [FACTION_TYPES.EXPLORERS, CL.VERY_LOW], [FACTION_TYPES.PERFORMERS, CL.EXTREMELY_LOW]])),
    STATE_RELIGION: new PolicyType('State Religion', NF.CULTURE, COLORS.White, [GT.TECHNOCRACY], [GT.THEOCRACY, GT.ARISTOCRACY], 
        [], [NT.RELIGION_REVIVAL, NT.CRACKDOWN, NT.LUDDITISM, NT.CULTURAL_PURGE, NT.RELIGION_INQUISITION], [],
        new Map([[FACTION_TYPES.INQUISITORS, CL.EXTREMELY_HIGH], [FACTION_TYPES.PILGRIMS, CL.VERY_HIGH], [FACTION_TYPES.MISSIONARIES, CL.VERY_HIGH], [FACTION_TYPES.SCIENTISTS, CL.VERY_LOW], [FACTION_TYPES.EXPLORERS, CL.LOW], [FACTION_TYPES.PERFORMERS, CL.SLIGHTLY_LOW]])),
    TOTALITARIANISM: new PolicyType('Totalitarianism', NF.CULTURE, COLORS.Brown, [GT.DEMOCRACY, GT.ANARCHY], [GT.POLICE_STATE], 
        [NT.REVOLUTION, NT.CRIME_WAVE], [NT.CRACKDOWN, NT.CONSCRIPTION, NT.FORCED_LABOR, NT.CULTURAL_PURGE, NT.EUGENICS, NT.TERRORISM, NT.RELIGION_INQUISITION], [],
        new Map([[FACTION_TYPES.POLICE, CL.EXTREMELY_HIGH], [FACTION_TYPES.SOLDIERS, CL.VERY_HIGH], [FACTION_TYPES.PIRATES, CL.EXTREMELY_LOW], [FACTION_TYPES.SMUGGLERS, CL.EXTREMELY_LOW], [FACTION_TYPES.TOURISTS, CL.EXTREMELY_LOW], [FACTION_TYPES.TAX_COLLECTORS, CL.EXTREMELY_HIGH], [FACTION_TYPES.REBELS, CL.VERY_HIGH], [FACTION_TYPES.REFUGEES, CL.EXTREMELY_HIGH], [FACTION_TYPES.MERCENARIES, CL.VERY_HIGH], [FACTION_TYPES.BOUNTY_HUNTERS, CL.EXTREMELY_HIGH], [FACTION_TYPES.SYNDICATES, CL.EXTREMELY_LOW], [FACTION_TYPES.EXPLORERS, CL.EXTREMELY_LOW], [FACTION_TYPES.PERFORMERS, CL.EXTREMELY_LOW]])),
    LIBERALISM: new PolicyType('Liberalism', NF.CULTURE, COLORS.Green, [GT.THEOCRACY, GT.POLICE_STATE], [GT.DEMOCRACY, GT.TECHNOCRACY], 
        [NT.CRACKDOWN, NT.GENOCIDE, NT.ENSLAVEMENT, NT.CULTURAL_PURGE, NT.EUGENICS, NT.RELIGION_INQUISITION], [NT.IMMIGRATION, NT.TOURISM, NT.CLONING, NT.CULTURAL_RENAISSANCE], [],
        new Map([[FACTION_TYPES.TOURISTS, CL.VERY_HIGH], [FACTION_TYPES.MERCHANTS, CL.HIGH], [FACTION_TYPES.COLONISTS, CL.HIGH], [FACTION_TYPES.SLAVERS, CL.EXTREMELY_LOW], [FACTION_TYPES.INQUISITORS, CL.EXTREMELY_LOW], [FACTION_TYPES.TAX_COLLECTORS, CL.LOW], [FACTION_TYPES.REBELS, CL.EXTREMELY_LOW], [FACTION_TYPES.REFUGEES, CL.VERY_LOW], [FACTION_TYPES.MERCENARIES, CL.SLIGHTLY_LOW], [FACTION_TYPES.BOUNTY_HUNTERS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.SYNDICATES, CL.SLIGHTLY_HIGH], [FACTION_TYPES.EXPLORERS, CL.VERY_HIGH], [FACTION_TYPES.PERFORMERS, CL.EXTREMELY_HIGH]])),
    
    // Military/Foreign Policy
    IMPERIALISM: new PolicyType('Imperialism', NF.POLITICS, COLORS.DarkPurple, [GT.ANARCHY, GT.PUPPET_STATE], [GT.POLICE_STATE, GT.ARISTOCRACY], 
        [NT.DISARMAMENT, NT.ISOLATIONISM], [NT.COLONIZATION, NT.WAR, NT.MILITARY_BUILDUP, NT.ENSLAVEMENT], [],
        new Map([[FACTION_TYPES.SOLDIERS, CL.EXTREMELY_HIGH], [FACTION_TYPES.COLONISTS, CL.VERY_HIGH], [FACTION_TYPES.SLAVERS, CL.HIGH], [FACTION_TYPES.TOURISTS, CL.VERY_LOW], [FACTION_TYPES.TAX_COLLECTORS, CL.HIGH], [FACTION_TYPES.REFUGEES, CL.VERY_HIGH], [FACTION_TYPES.MERCENARIES, CL.EXTREMELY_HIGH], [FACTION_TYPES.EXPLORERS, CL.HIGH], [FACTION_TYPES.PERFORMERS, CL.LOW]])),
    ISOLATIONISM: new PolicyType('Isolationism', NF.POLITICS, COLORS.Gray, [GT.PUPPET_STATE], [GT.POLICE_STATE, GT.THEOCRACY], 
        [NT.ALLIANCE, NT.TRADE_AGREEMENT, NT.FOREIGN_AID, NT.WAR, NT.BLOCKADE, NT.SANCTIONS, NT.TERRORISM], [NT.DISARMAMENT], [],
        new Map([[FACTION_TYPES.MERCHANTS, CL.EXTREMELY_LOW], [FACTION_TYPES.SOLDIERS, CL.EXTREMELY_LOW], [FACTION_TYPES.TOURISTS, CL.EXTREMELY_LOW], [FACTION_TYPES.COLONISTS, CL.EXTREMELY_LOW], [FACTION_TYPES.MINERS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.SCIENTISTS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.DIPLOMATS, CL.EXTREMELY_LOW], [FACTION_TYPES.SALVAGERS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.MERCENARIES, CL.EXTREMELY_LOW], [FACTION_TYPES.BOUNTY_HUNTERS, CL.LOW], [FACTION_TYPES.SYNDICATES, CL.LOW], [FACTION_TYPES.EXPLORERS, CL.EXTREMELY_LOW], [FACTION_TYPES.PERFORMERS, CL.EXTREMELY_LOW]])),
    COMMERCIALISM: new PolicyType('Commercialism', NF.POLITICS, COLORS.Yellow, [], [GT.DEMOCRACY, GT.CORPORATISM], 
        [NT.ISOLATIONISM, NT.BLOCKADE], [NT.TRADE_AGREEMENT, NT.INVESTMENT, NT.TOURISM], [],
        new Map([[FACTION_TYPES.MERCHANTS, CL.VERY_HIGH], [FACTION_TYPES.TOURISTS, CL.VERY_HIGH], [FACTION_TYPES.SOLDIERS, CL.LOW], [FACTION_TYPES.PIRATES, CL.SLIGHTLY_HIGH], [FACTION_TYPES.DIPLOMATS, CL.HIGH], [FACTION_TYPES.SALVAGERS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.MERCENARIES, CL.HIGH], [FACTION_TYPES.BOUNTY_HUNTERS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.SYNDICATES, CL.HIGH], [FACTION_TYPES.EXPLORERS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.PERFORMERS, CL.EXTREMELY_HIGH]])),
    UNIVERSALISM: new PolicyType('Universalism', NF.POLITICS, COLORS.LightGreen, [GT.POLICE_STATE], [GT.DEMOCRACY, GT.THEOCRACY], 
        [NT.GENOCIDE, NT.LAND_GRAB, NT.ENSLAVEMENT, NT.TERRORISM], [NT.ALLIANCE, NT.FOREIGN_AID, NT.IMMIGRATION], [],
        new Map([[FACTION_TYPES.COLONISTS, CL.HIGH], [FACTION_TYPES.MISSIONARIES, CL.VERY_HIGH], [FACTION_TYPES.TOURISTS, CL.HIGH], [FACTION_TYPES.SOLDIERS, CL.LOW], [FACTION_TYPES.SLAVERS, CL.EXTREMELY_LOW], [FACTION_TYPES.DIPLOMATS, CL.VERY_HIGH], [FACTION_TYPES.REFUGEES, CL.EXTREMELY_LOW], [FACTION_TYPES.EXPLORERS, CL.HIGH], [FACTION_TYPES.PERFORMERS, CL.VERY_HIGH]])),

    //Religious policy
    POLYTHEISM: new PolicyType('Polytheism', NF.RELIGION, COLORS.Orange, [], [GT.DEMOCRACY, GT.ARISTOCRACY], 
        [NT.RELIGION_INQUISITION], [NT.RELIGION_REVIVAL, NT.IMMIGRATION], [],
        new Map([[FACTION_TYPES.PILGRIMS, CL.HIGH], [FACTION_TYPES.MISSIONARIES, CL.SLIGHTLY_HIGH], [FACTION_TYPES.INQUISITORS, CL.EXTREMELY_LOW], [FACTION_TYPES.TOURISTS, CL.SLIGHTLY_HIGH], [FACTION_TYPES.PERFORMERS, CL.HIGH]])),
    MONOTHEISM: new PolicyType('Monotheism', NF.RELIGION, COLORS.LightBlue, [], [GT.THEOCRACY, GT.ARISTOCRACY], 
        [], [NT.RELIGION_REVIVAL, NT.RELIGION_INQUISITION, NT.CULTURAL_PURGE], [],
        new Map([[FACTION_TYPES.INQUISITORS, CL.VERY_HIGH], [FACTION_TYPES.PILGRIMS, CL.VERY_HIGH], [FACTION_TYPES.MISSIONARIES, CL.VERY_HIGH], [FACTION_TYPES.SCIENTISTS, CL.LOW], [FACTION_TYPES.EXPLORERS, CL.SLIGHTLY_LOW], [FACTION_TYPES.PERFORMERS, CL.LOW]])),
    SECULARISM: new PolicyType('Secularism', NF.RELIGION, COLORS.Blue, [GT.THEOCRACY], [GT.DEMOCRACY, GT.TECHNOCRACY], 
        [NT.RELIGION_REVIVAL, NT.RELIGION_INQUISITION], [NT.CULTURAL_RENAISSANCE, NT.SCIENTIFIC_BREAKTHROUGH], [],
        new Map([[FACTION_TYPES.SCIENTISTS, CL.VERY_HIGH], [FACTION_TYPES.PILGRIMS, CL.EXTREMELY_LOW], [FACTION_TYPES.INQUISITORS, CL.EXTREMELY_LOW], [FACTION_TYPES.MISSIONARIES, CL.EXTREMELY_LOW], [FACTION_TYPES.EXPLORERS, CL.VERY_HIGH], [FACTION_TYPES.PERFORMERS, CL.HIGH]])),
    ATHEISM: new PolicyType('Atheism', NF.RELIGION, COLORS.Gray, [GT.THEOCRACY], [GT.COMMUNISM, GT.TECHNOCRACY], 
        [NT.RELIGION_REVIVAL, NT.RELIGION_INQUISITION], [NT.LUDDITISM, NT.SCIENTIFIC_BREAKTHROUGH], [],
        new Map([[FACTION_TYPES.SCIENTISTS, CL.VERY_HIGH], [FACTION_TYPES.PILGRIMS, CL.EXTREMELY_LOW], [FACTION_TYPES.INQUISITORS, CL.EXTREMELY_LOW], [FACTION_TYPES.MISSIONARIES, CL.EXTREMELY_LOW], [FACTION_TYPES.EXPLORERS, CL.VERY_HIGH], [FACTION_TYPES.PERFORMERS, CL.SLIGHTLY_HIGH]])),
}

const PT_ALL = Object.values(PT)

/** @type {PolicyType[]} */
const ECONOMIC_POLICIES = [PT.DECENTRALIZATION, PT.PROTECTIONISM, PT.CENTRAL_PLANNING, PT.FREE_TRADE]

/** @type {PolicyType[]} */
const LABOR_POLICIES = [PT.FORCED_LABOR, PT.FEUDALISM, PT.LAISSEZ_FAIRE, PT.LABOR_UNIONS]

/** @type {PolicyType[]} */
const SOCIAL_POLICIES = [PT.ETHNIC_NATIONALISM, PT.STATE_RELIGION, PT.TOTALITARIANISM, PT.LIBERALISM]

/** @type {PolicyType[]} */
const FOREIGN_POLICIES = [PT.IMPERIALISM, PT.ISOLATIONISM, PT.COMMERCIALISM, PT.UNIVERSALISM]


